Merge branch '2.3' of ezsystems/ez-support-tools into main
ibexa/system-info pull request #30
Opened 2022-02-02 13:20 UTC by ezrobot

Cross merge PR

2022-02-03 08:07 UTC, konradoboza requested changes

2022-02-03 08:07 UTC, konradoboza commented on composer.json
> +        "php": "^7.3 || ^8.0",
```suggestion
        "php": "^7.4 || ^8.0",
```

2022-02-16 09:07 UTC, adamwojs commented
Rebase is needed here

2022-02-18 13:16 UTC, merged

2022-02-18 13:16 UTC, alongosz commented
Merged via 8eaa96a.