Fixed code style and added more strict typing to `SystemInfoDumpCommand`
ibexa/system-info pull request #35
Opened 2022-10-20 14:00 UTC by konradoboza

I noticed some failing CS and some nitpicks in the affected Command.

2022-10-20 14:04 UTC, webhdx approved these changes

2022-10-20 14:34 UTC, alongosz reviewed
@konradoboza does this apply to `main` only?

2022-10-20 14:46 UTC, konradoboza commented
It seems `4.2` is also affected. Rebased, thanks for pointing that out @alongosz.

2022-10-20 14:50 UTC, alongosz requested changes

2022-10-20 14:50 UTC, alongosz commented on .github/workflows/browser-tests.yaml
> +            project-version: '4.3.x-dev'
You can skip it now ;)

2022-10-20 14:50 UTC, alongosz commented on composer.json
> +        "ibexa/http-cache": "~4.3.0@dev",
Seems like this rebase didn't go so well. I feel responsible for making the fuss :sweat_smile:

2022-10-20 14:55 UTC, alongosz approved these changes

2022-10-20 17:13 UTC, Steveb-p approved these changes

2022-10-21 06:06 UTC, merged

2022-10-21 06:08 UTC, konradoboza commented
Merged up via https://github.com/ibexa/system-info/commit/cca60172d907368cb24797a5b1c1b3f90baed9e0.